### ISSUE TITLE
TypeError: this.expires.toUTCString is not a function

### ISSUE THREAD

**Issue by sudhiryadav** [iroy2000/redux-cookie#5]
I am getting this error could you share what could be wrong?

Stack trace: 

TypeError: this.expires.toUTCString is not a function
at Cookie.toHeader (/Users/xxxx/Documents/Projectsnode_modules/cookies/index.js:168:61)
at pushCookie (/Users/xxxx/Documents/Projectsnode_modules/cookies/index.js:200:23)
at Cookies.set (/Users/xxxx/Documents/Projectsnode_modules/cookies/index.js:105:13)
at actionsMap.(anonymous function) (/Users/xxxx/Documents/Projectsnode_modules/redux-cookie/lib/index.js:52:20)
at /Users/xxxx/Documents/Projectsnode_modules/redux-cookie/lib/index.js:79:18
at /Users/xxxx/Documents/Projectsnode_modules/redux-thunk/lib/index.js:14:16
at Object.dispatch (/Users/xxxx/Documents/Projectsshared/lib/promiseMiddleware.js:5:14)
at setUserCookie (/Users/xxxx/Documents/Projectsshared/lib/cookies.js:43:10)
at getUserCookie (/Users/xxxx/Documents/Projectsshared/lib/cookies.js:10:9)
at RadiumEnhancer.SideBar (/Users/xxxx/Documents/Projectsshared/components/SideBar.jsx:24:20)
at new RadiumEnhancer (/Users/xxxx/Documents/Projectsnode_modules/radium/lib/enhancer.js:85:72)
at /Users/xxxx/Documents/Projectsnode_modules/react-dom/lib/ReactCompositeComponent.js:295:18
at measureLifeCyclePerf 

This is the method it is giving error:

`export function setUserCookie(user) {
    window
        .store
        .dispatch(setCookie('user', user, {expires: 365}))
}`

**Comment by iroy2000** [comment]
Hi @sudhiryadav 

Which cookie library you are using in your middleware ?

The short answer is you might want to try 

```javascript
export function setUserCookie(user) { 
  window .store .dispatch(setCookie('user', user, {expires: new Date(Date.now() + 365})) 
}
```

`expires.toUTCString is not a function` means it is expecting a Date object.

**Comment by sudhiryadav** [comment]
Hi @iroy2000,

Yes that indeed was the issue. So, now when i refresh the page i am not getting this error. But however there is a different issue.

It seems that redux-cookie is storing the cookie but is not able to retrieve the same. Here are some logs from chrome debugger console.

window
        .store
        .dispatch(setCookie1(USER_COOKIE_NAME, user,{expires}));

index.jsx:33 _user={%22_id%22:%2259ccf4ce69738a2c2bfd4be6%22%2C%22_roleId%22:{%22_id%22:%22587d09f693e118012679f7c5%22%2C%22roleId%22:3%2C%22name%22:%22public%22}%2C%22emailVerificaionCode%22:4581%2C%22phoneVerficationCode%22:2463%2C%22firstName%22:%22Sudhir%22%2C%22lastName%22:%22Yadav%22%2C%22fiscalCode%22:%22BTALVI36A24F471R%22%2C%22email%22:%22er.sudhir.yadav@gmail.com%22%2C%22dateOfBirth%22:%221936-01-23T18:30:00.000Z%22%2C%22_munipalityOfBirthId%22:{%22_id%22:17113%2C%22name%22:%22Montichiari%22%2C%22code%22:%22F471%22}%2C%22gender%22:%22M%22%2C%22mobilePhone%22:%22+39%209999999999%22%2C%22password%22:%221%22%2C%22isEmailVerified%22:true%2C%22isPhoneVerified%22:false%2C%22doctorInfo%22:{%22_examIds%22:[]}%2C%22__v%22:0}; path=/; expires=Wed, 03 Oct 2018 09:58:58 GMT


window
        .store
        .dispatch(getCookie1(USER_COOKIE_NAME));
index.jsx:33 undefined



Do you have any idea why is it returning undefined. I could also sense somewhere that the problem could be in cookie.get(action.name) which is returning undefined.

**Comment by sudhiryadav** [comment]
Thanks that indeed was the issue of the date passed in wrong format.
