### ISSUE TITLE
Cannot get cookie

### ISSUE THREAD

**Issue by erperejildo** [iroy2000/redux-cookie#6]
```
setCookie('test', 'this needs to be updated', { expires: 365 });
console.log('COOKIE ', getCookie('test'));
```

I can't get the content:
<img width="409" alt="screen shot 2017-11-30 at 10 54 00" src="https://user-images.githubusercontent.com/5629919/33427303-ccaf565c-d5bc-11e7-9be2-11da1302003d.png">

**Comment by lucaspedroza1** [comment]
I can't get the content too. I did something wrong?

Regards

**Comment by erperejildo** [comment]
@lucaspedroza1 I can't remember what I changed (and I don't even working on same project) but definitely was my fault. Sorry

**Comment by lucaspedroza1** [comment]
Ok @erperejildo Thanks!

**Comment by CarloSaccone** [comment]
I have the same problem, followed installation instructions, but cannot retrieve the stored value...what am I missing?
